/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ThriftIdleTimeoutWarningEvent_TYPES_H
#define ThriftIdleTimeoutWarningEvent_TYPES_H

#include <iosfwd>

#include "libs/Thrift.h"

#include "libs/TProtocol.h"
#include "libs/TTransport.h"




namespace es {

class ThriftIdleTimeoutWarningEvent;


class ThriftIdleTimeoutWarningEvent {
 public:

  ThriftIdleTimeoutWarningEvent(const ThriftIdleTimeoutWarningEvent&);
  ThriftIdleTimeoutWarningEvent& operator=(const ThriftIdleTimeoutWarningEvent&);
  ThriftIdleTimeoutWarningEvent() {
  }

  virtual ~ThriftIdleTimeoutWarningEvent() throw();

  bool operator == (const ThriftIdleTimeoutWarningEvent & /* rhs */) const
  {
    return true;
  }
  bool operator != (const ThriftIdleTimeoutWarningEvent &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftIdleTimeoutWarningEvent & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(ThriftIdleTimeoutWarningEvent &a, ThriftIdleTimeoutWarningEvent &b);

inline std::ostream& operator<<(std::ostream& out, const ThriftIdleTimeoutWarningEvent& obj)
{
  obj.printTo(out);
  return out;
}

} // namespace

#endif
