/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ThriftZoneListEntry_types.h"

#include <algorithm>
#include <ostream>

#include "libs/TToString.h"

namespace es {


ThriftZoneListEntry::~ThriftZoneListEntry() throw() {
}


void ThriftZoneListEntry::__set_zoneId(const int32_t val) {
  this->zoneId = val;
}

void ThriftZoneListEntry::__set_zoneName(const std::string& val) {
  this->zoneName = val;
}

uint32_t ThriftZoneListEntry::read(::apache::thrift::protocol::TProtocol* iprot) {

  apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->zoneId);
          this->__isset.zoneId = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->zoneName);
          this->__isset.zoneName = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t ThriftZoneListEntry::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ThriftZoneListEntry");

  xfer += oprot->writeFieldBegin("zoneId", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->zoneId);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("zoneName", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->zoneName);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ThriftZoneListEntry &a, ThriftZoneListEntry &b) {
  using ::std::swap;
  swap(a.zoneId, b.zoneId);
  swap(a.zoneName, b.zoneName);
  swap(a.__isset, b.__isset);
}

ThriftZoneListEntry::ThriftZoneListEntry(const ThriftZoneListEntry& other0) {
  zoneId = other0.zoneId;
  zoneName = other0.zoneName;
  __isset = other0.__isset;
}
ThriftZoneListEntry& ThriftZoneListEntry::operator=(const ThriftZoneListEntry& other1) {
  zoneId = other1.zoneId;
  zoneName = other1.zoneName;
  __isset = other1.__isset;
  return *this;
}
void ThriftZoneListEntry::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ThriftZoneListEntry(";
  out << "zoneId=" << to_string(zoneId);
  out << ", " << "zoneName=" << to_string(zoneName);
  out << ")";
}

} // namespace
