/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ThriftDeleteUserVariableRequest_types.h"

#include <algorithm>
#include <ostream>

#include "libs/TToString.h"

namespace es {


ThriftDeleteUserVariableRequest::~ThriftDeleteUserVariableRequest() throw() {
}


void ThriftDeleteUserVariableRequest::__set_name(const std::string& val) {
  this->name = val;
}

uint32_t ThriftDeleteUserVariableRequest::read(::apache::thrift::protocol::TProtocol* iprot) {

  apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->name);
          this->__isset.name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t ThriftDeleteUserVariableRequest::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ThriftDeleteUserVariableRequest");

  xfer += oprot->writeFieldBegin("name", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->name);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ThriftDeleteUserVariableRequest &a, ThriftDeleteUserVariableRequest &b) {
  using ::std::swap;
  swap(a.name, b.name);
  swap(a.__isset, b.__isset);
}

ThriftDeleteUserVariableRequest::ThriftDeleteUserVariableRequest(const ThriftDeleteUserVariableRequest& other0) {
  name = other0.name;
  __isset = other0.__isset;
}
ThriftDeleteUserVariableRequest& ThriftDeleteUserVariableRequest::operator=(const ThriftDeleteUserVariableRequest& other1) {
  name = other1.name;
  __isset = other1.__isset;
  return *this;
}
void ThriftDeleteUserVariableRequest::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ThriftDeleteUserVariableRequest(";
  out << "name=" << to_string(name);
  out << ")";
}

} // namespace
