/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ThriftProtocol_types.h"

#include <algorithm>
#include <ostream>

#include "libs/TToString.h"

namespace es {

//int _kThriftProtocolValues[] = {
//  ThriftProtocol::ThriftProtocol_BinaryTCP,
//  ThriftProtocol::ThriftProtocol_RTMP,
//  ThriftProtocol::ThriftProtocol_BinaryHTTP,
//  ThriftProtocol::ThriftProtocol_TextTCP,
//  ThriftProtocol::ThriftProtocol_BinaryUDP
//};
//const char* _kThriftProtocolNames[] = {
//  "ThriftProtocol_BinaryTCP",
//  "ThriftProtocol_RTMP",
//  "ThriftProtocol_BinaryHTTP",
//  "ThriftProtocol_TextTCP",
//  "ThriftProtocol_BinaryUDP"
//};
//const std::map<int, const char*> _ThriftProtocol_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(5, _kThriftProtocolValues, _kThriftProtocolNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));

} // namespace
