/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ThriftFlattenedEsObjectRO_TYPES_H
#define ThriftFlattenedEsObjectRO_TYPES_H

#include <iosfwd>

#include "libs/Thrift.h"

#include "libs/TProtocol.h"
#include "libs/TTransport.h"




namespace es {

class ThriftFlattenedEsObjectRO;

typedef struct _ThriftFlattenedEsObjectRO__isset {
  _ThriftFlattenedEsObjectRO__isset() : encodedEntries(false) {}
  bool encodedEntries :1;
} _ThriftFlattenedEsObjectRO__isset;

class ThriftFlattenedEsObjectRO {
 public:

  ThriftFlattenedEsObjectRO(const ThriftFlattenedEsObjectRO&);
  ThriftFlattenedEsObjectRO& operator=(const ThriftFlattenedEsObjectRO&);
  ThriftFlattenedEsObjectRO() {
  }

  virtual ~ThriftFlattenedEsObjectRO() throw();
  std::vector<int8_t>  encodedEntries;

  _ThriftFlattenedEsObjectRO__isset __isset;

  void __set_encodedEntries(const std::vector<int8_t> & val);

  bool operator == (const ThriftFlattenedEsObjectRO & rhs) const
  {
    if (!(encodedEntries == rhs.encodedEntries))
      return false;
    return true;
  }
  bool operator != (const ThriftFlattenedEsObjectRO &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftFlattenedEsObjectRO & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(ThriftFlattenedEsObjectRO &a, ThriftFlattenedEsObjectRO &b);

inline std::ostream& operator<<(std::ostream& out, const ThriftFlattenedEsObjectRO& obj)
{
  obj.printTo(out);
  return out;
}

} // namespace

#endif
