/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ThriftUserServerVariable_TYPES_H
#define ThriftUserServerVariable_TYPES_H

#include <iosfwd>

#include "libs/Thrift.h"

#include "libs/TProtocol.h"
#include "libs/TTransport.h"


#include "ThriftFlattenedEsObject_types.h"


namespace es {

class ThriftUserServerVariable;

typedef struct _ThriftUserServerVariable__isset {
  _ThriftUserServerVariable__isset() : name(false), value(false) {}
  bool name :1;
  bool value :1;
} _ThriftUserServerVariable__isset;

class ThriftUserServerVariable {
 public:

  ThriftUserServerVariable(const ThriftUserServerVariable&);
  ThriftUserServerVariable& operator=(const ThriftUserServerVariable&);
  ThriftUserServerVariable() : name() {
  }

  virtual ~ThriftUserServerVariable() throw();
  std::string name;
   ::es::ThriftFlattenedEsObject value;

  _ThriftUserServerVariable__isset __isset;

  void __set_name(const std::string& val);

  void __set_value(const  ::es::ThriftFlattenedEsObject& val);

  bool operator == (const ThriftUserServerVariable & rhs) const
  {
    if (!(name == rhs.name))
      return false;
    if (!(value == rhs.value))
      return false;
    return true;
  }
  bool operator != (const ThriftUserServerVariable &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftUserServerVariable & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(ThriftUserServerVariable &a, ThriftUserServerVariable &b);

inline std::ostream& operator<<(std::ostream& out, const ThriftUserServerVariable& obj)
{
  obj.printTo(out);
  return out;
}

} // namespace

#endif
