/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ThriftUserUpdateAction_types.h"

#include <algorithm>
#include <ostream>

#include "libs/TToString.h"

namespace es {

//int _kThriftUserUpdateActionValues[] = {
//  ThriftUserUpdateAction::ThriftUserUpdateAction_AddUser,
//  ThriftUserUpdateAction::ThriftUserUpdateAction_DeleteUser,
//  ThriftUserUpdateAction::ThriftUserUpdateAction_OperatorGranted,
//  ThriftUserUpdateAction::ThriftUserUpdateAction_OperatorRevoked,
//  ThriftUserUpdateAction::ThriftUserUpdateAction_SendingVideoStream,
//  ThriftUserUpdateAction::ThriftUserUpdateAction_StoppingVideoStream
//};
//const char* _kThriftUserUpdateActionNames[] = {
//  "ThriftUserUpdateAction_AddUser",
//  "ThriftUserUpdateAction_DeleteUser",
//  "ThriftUserUpdateAction_OperatorGranted",
//  "ThriftUserUpdateAction_OperatorRevoked",
//  "ThriftUserUpdateAction_SendingVideoStream",
//  "ThriftUserUpdateAction_StoppingVideoStream"
//};
//const std::map<int, const char*> _ThriftUserUpdateAction_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(6, _kThriftUserUpdateActionValues, _kThriftUserUpdateActionNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));

} // namespace
