/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ThriftDataType_types.h"

#include <algorithm>
#include <ostream>

#include "libs/TToString.h"

namespace es {

//int _kThriftDataTypeValues[] = {
//  ThriftDataType::ThriftDataType_Integer,
//  ThriftDataType::ThriftDataType_String,
//  ThriftDataType::ThriftDataType_Double,
//  ThriftDataType::ThriftDataType_Float,
//  ThriftDataType::ThriftDataType_Boolean,
//  ThriftDataType::ThriftDataType_Byte,
//  ThriftDataType::ThriftDataType_Character,
//  ThriftDataType::ThriftDataType_Long,
//  ThriftDataType::ThriftDataType_Short,
//  ThriftDataType::ThriftDataType_EsObject,
//  ThriftDataType::ThriftDataType_EsObjectArray,
//  ThriftDataType::ThriftDataType_IntegerArray,
//  ThriftDataType::ThriftDataType_StringArray,
//  ThriftDataType::ThriftDataType_DoubleArray,
//  ThriftDataType::ThriftDataType_FloatArray,
//  ThriftDataType::ThriftDataType_BooleanArray,
//  ThriftDataType::ThriftDataType_ByteArray,
//  ThriftDataType::ThriftDataType_CharacterArray,
//  ThriftDataType::ThriftDataType_LongArray,
//  ThriftDataType::ThriftDataType_ShortArray,
//  ThriftDataType::ThriftDataType_Number,
//  ThriftDataType::ThriftDataType_NumberArray
//};
//const char* _kThriftDataTypeNames[] = {
//  "ThriftDataType_Integer",
//  "ThriftDataType_String",
//  "ThriftDataType_Double",
//  "ThriftDataType_Float",
//  "ThriftDataType_Boolean",
//  "ThriftDataType_Byte",
//  "ThriftDataType_Character",
//  "ThriftDataType_Long",
//  "ThriftDataType_Short",
//  "ThriftDataType_EsObject",
//  "ThriftDataType_EsObjectArray",
//  "ThriftDataType_IntegerArray",
//  "ThriftDataType_StringArray",
//  "ThriftDataType_DoubleArray",
//  "ThriftDataType_FloatArray",
//  "ThriftDataType_BooleanArray",
//  "ThriftDataType_ByteArray",
//  "ThriftDataType_CharacterArray",
//  "ThriftDataType_LongArray",
//  "ThriftDataType_ShortArray",
//  "ThriftDataType_Number",
//  "ThriftDataType_NumberArray"
//};
//const std::map<int, const char*> _ThriftDataType_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(22, _kThriftDataTypeValues, _kThriftDataTypeNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));

} // namespace
