/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ThriftGetGameTypesResponse_types.h"

#include <algorithm>
#include <ostream>

#include "libs/TToString.h"

namespace es {


ThriftGetGameTypesResponse::~ThriftGetGameTypesResponse() throw() {
}


void ThriftGetGameTypesResponse::__set_gameTypes(const std::vector<std::string> & val) {
  this->gameTypes = val;
}

uint32_t ThriftGetGameTypesResponse::read(::apache::thrift::protocol::TProtocol* iprot) {

  apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->gameTypes.clear();
            uint32_t _size0;
            ::apache::thrift::protocol::TType _etype3;
            xfer += iprot->readListBegin(_etype3, _size0);
            this->gameTypes.resize(_size0);
            uint32_t _i4;
            for (_i4 = 0; _i4 < _size0; ++_i4)
            {
              xfer += iprot->readString(this->gameTypes[_i4]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.gameTypes = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t ThriftGetGameTypesResponse::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ThriftGetGameTypesResponse");

  xfer += oprot->writeFieldBegin("gameTypes", ::apache::thrift::protocol::T_LIST, 1);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->gameTypes.size()));
    std::vector<std::string> ::const_iterator _iter5;
    for (_iter5 = this->gameTypes.begin(); _iter5 != this->gameTypes.end(); ++_iter5)
    {
      xfer += oprot->writeString((*_iter5));
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ThriftGetGameTypesResponse &a, ThriftGetGameTypesResponse &b) {
  using ::std::swap;
  swap(a.gameTypes, b.gameTypes);
  swap(a.__isset, b.__isset);
}

ThriftGetGameTypesResponse::ThriftGetGameTypesResponse(const ThriftGetGameTypesResponse& other6) {
  gameTypes = other6.gameTypes;
  __isset = other6.__isset;
}
ThriftGetGameTypesResponse& ThriftGetGameTypesResponse::operator=(const ThriftGetGameTypesResponse& other7) {
  gameTypes = other7.gameTypes;
  __isset = other7.__isset;
  return *this;
}
void ThriftGetGameTypesResponse::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ThriftGetGameTypesResponse(";
  out << "gameTypes=" << to_string(gameTypes);
  out << ")";
}

} // namespace
