/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ThriftConnectionResponse_TYPES_H
#define ThriftConnectionResponse_TYPES_H

#include <iosfwd>

#include "libs/Thrift.h"

#include "libs/TProtocol.h"
#include "libs/TTransport.h"


#include "ThriftProtocolConfiguration_types.h"
#include "ThriftErrorType_types.h"


namespace es {

class ThriftConnectionResponse;

typedef struct _ThriftConnectionResponse__isset {
  _ThriftConnectionResponse__isset() : successful(false), hashId(false), error(false), protocolConfiguration(false), serverVersion(false) {}
  bool successful :1;
  bool hashId :1;
  bool error :1;
  bool protocolConfiguration :1;
  bool serverVersion :1;
} _ThriftConnectionResponse__isset;

class ThriftConnectionResponse {
 public:

  ThriftConnectionResponse(const ThriftConnectionResponse&);
  ThriftConnectionResponse& operator=(const ThriftConnectionResponse&);
  ThriftConnectionResponse() : successful(0), hashId(0), error(( ::es::ThriftErrorType::type)0), serverVersion() {
  }

  virtual ~ThriftConnectionResponse() throw();
  bool successful;
  int32_t hashId;
   ::es::ThriftErrorType::type error;
   ::es::ThriftProtocolConfiguration protocolConfiguration;
  std::string serverVersion;

  _ThriftConnectionResponse__isset __isset;

  void __set_successful(const bool val);

  void __set_hashId(const int32_t val);

  void __set_error(const  ::es::ThriftErrorType::type val);

  void __set_protocolConfiguration(const  ::es::ThriftProtocolConfiguration& val);

  void __set_serverVersion(const std::string& val);

  bool operator == (const ThriftConnectionResponse & rhs) const
  {
    if (!(successful == rhs.successful))
      return false;
    if (!(hashId == rhs.hashId))
      return false;
    if (!(error == rhs.error))
      return false;
    if (!(protocolConfiguration == rhs.protocolConfiguration))
      return false;
    if (!(serverVersion == rhs.serverVersion))
      return false;
    return true;
  }
  bool operator != (const ThriftConnectionResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftConnectionResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(ThriftConnectionResponse &a, ThriftConnectionResponse &b);

inline std::ostream& operator<<(std::ostream& out, const ThriftConnectionResponse& obj)
{
  obj.printTo(out);
  return out;
}

} // namespace

#endif
