/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ThriftPrivateMessageEvent_TYPES_H
#define ThriftPrivateMessageEvent_TYPES_H

#include <iosfwd>

#include "libs/Thrift.h"
//
#include "libs/TProtocol.h"
#include "libs/TTransport.h"

//
#include "ThriftFlattenedEsObject_types.h"


namespace es {

class ThriftPrivateMessageEvent;

typedef struct _ThriftPrivateMessageEvent__isset {
  _ThriftPrivateMessageEvent__isset() : userName(false), message(false), esObject(false) {}
  bool userName :1;
  bool message :1;
  bool esObject :1;
} _ThriftPrivateMessageEvent__isset;

class ThriftPrivateMessageEvent {
 public:

  ThriftPrivateMessageEvent(const ThriftPrivateMessageEvent&);
  ThriftPrivateMessageEvent& operator=(const ThriftPrivateMessageEvent&);
  ThriftPrivateMessageEvent() : userName(), message() {
  }

  virtual ~ThriftPrivateMessageEvent() throw();
  std::string userName;
  std::string message;
   ::es::ThriftFlattenedEsObject esObject;

  _ThriftPrivateMessageEvent__isset __isset;

  void __set_userName(const std::string& val);

  void __set_message(const std::string& val);

  void __set_esObject(const  ::es::ThriftFlattenedEsObject& val);

  bool operator == (const ThriftPrivateMessageEvent & rhs) const
  {
    if (__isset.userName != rhs.__isset.userName)
      return false;
    else if (__isset.userName && !(userName == rhs.userName))
      return false;
    if (__isset.message != rhs.__isset.message)
      return false;
    else if (__isset.message && !(message == rhs.message))
      return false;
    if (__isset.esObject != rhs.__isset.esObject)
      return false;
    else if (__isset.esObject && !(esObject == rhs.esObject))
      return false;
    return true;
  }
  bool operator != (const ThriftPrivateMessageEvent &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftPrivateMessageEvent & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(ThriftPrivateMessageEvent &a, ThriftPrivateMessageEvent &b);

inline std::ostream& operator<<(std::ostream& out, const ThriftPrivateMessageEvent& obj)
{
  obj.printTo(out);
  return out;
}

} // namespace

#endif
