/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ThriftValidateAdditionalLoginResponse_types.h"

#include <algorithm>
#include <ostream>

#include "libs/TToString.h"

namespace es {


ThriftValidateAdditionalLoginResponse::~ThriftValidateAdditionalLoginResponse() throw() {
}


void ThriftValidateAdditionalLoginResponse::__set_approved(const bool val) {
  this->approved = val;
}

void ThriftValidateAdditionalLoginResponse::__set_secret(const std::string& val) {
  this->secret = val;
}

uint32_t ThriftValidateAdditionalLoginResponse::read(::apache::thrift::protocol::TProtocol* iprot) {

  apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->approved);
          this->__isset.approved = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->secret);
          this->__isset.secret = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t ThriftValidateAdditionalLoginResponse::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ThriftValidateAdditionalLoginResponse");

  xfer += oprot->writeFieldBegin("approved", ::apache::thrift::protocol::T_BOOL, 1);
  xfer += oprot->writeBool(this->approved);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("secret", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->secret);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ThriftValidateAdditionalLoginResponse &a, ThriftValidateAdditionalLoginResponse &b) {
  using ::std::swap;
  swap(a.approved, b.approved);
  swap(a.secret, b.secret);
  swap(a.__isset, b.__isset);
}

ThriftValidateAdditionalLoginResponse::ThriftValidateAdditionalLoginResponse(const ThriftValidateAdditionalLoginResponse& other0) {
  approved = other0.approved;
  secret = other0.secret;
  __isset = other0.__isset;
}
ThriftValidateAdditionalLoginResponse& ThriftValidateAdditionalLoginResponse::operator=(const ThriftValidateAdditionalLoginResponse& other1) {
  approved = other1.approved;
  secret = other1.secret;
  __isset = other1.__isset;
  return *this;
}
void ThriftValidateAdditionalLoginResponse::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ThriftValidateAdditionalLoginResponse(";
  out << "approved=" << to_string(approved);
  out << ", " << "secret=" << to_string(secret);
  out << ")";
}

} // namespace
