/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ThriftGetServerLocalTimeResponse_types.h"

#include <algorithm>
#include <ostream>

#include "libs/TToString.h"

namespace es {


ThriftGetServerLocalTimeResponse::~ThriftGetServerLocalTimeResponse() throw() {
}


void ThriftGetServerLocalTimeResponse::__set_serverLocalTimeInMilliseconds(const int64_t val) {
  this->serverLocalTimeInMilliseconds = val;
}

uint32_t ThriftGetServerLocalTimeResponse::read(::apache::thrift::protocol::TProtocol* iprot) {

  apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->serverLocalTimeInMilliseconds);
          this->__isset.serverLocalTimeInMilliseconds = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t ThriftGetServerLocalTimeResponse::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ThriftGetServerLocalTimeResponse");

  xfer += oprot->writeFieldBegin("serverLocalTimeInMilliseconds", ::apache::thrift::protocol::T_I64, 1);
  xfer += oprot->writeI64(this->serverLocalTimeInMilliseconds);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ThriftGetServerLocalTimeResponse &a, ThriftGetServerLocalTimeResponse &b) {
  using ::std::swap;
  swap(a.serverLocalTimeInMilliseconds, b.serverLocalTimeInMilliseconds);
  swap(a.__isset, b.__isset);
}

ThriftGetServerLocalTimeResponse::ThriftGetServerLocalTimeResponse(const ThriftGetServerLocalTimeResponse& other0) {
  serverLocalTimeInMilliseconds = other0.serverLocalTimeInMilliseconds;
  __isset = other0.__isset;
}
ThriftGetServerLocalTimeResponse& ThriftGetServerLocalTimeResponse::operator=(const ThriftGetServerLocalTimeResponse& other1) {
  serverLocalTimeInMilliseconds = other1.serverLocalTimeInMilliseconds;
  __isset = other1.__isset;
  return *this;
}
void ThriftGetServerLocalTimeResponse::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ThriftGetServerLocalTimeResponse(";
  out << "serverLocalTimeInMilliseconds=" << to_string(serverLocalTimeInMilliseconds);
  out << ")";
}

} // namespace
