/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ThriftDataType_TYPES_H
#define ThriftDataType_TYPES_H

#include <iosfwd>

#include "libs/Thrift.h"

#include "libs/TProtocol.h"
#include "libs/TTransport.h"




namespace es {

struct ThriftDataType {
  enum type {
    ThriftDataType_Integer = 1,
    ThriftDataType_String = 2,
    ThriftDataType_Double = 3,
    ThriftDataType_Float = 4,
    ThriftDataType_Boolean = 5,
    ThriftDataType_Byte = 6,
    ThriftDataType_Character = 7,
    ThriftDataType_Long = 8,
    ThriftDataType_Short = 9,
    ThriftDataType_EsObject = 10,
    ThriftDataType_EsObjectArray = 11,
    ThriftDataType_IntegerArray = 12,
    ThriftDataType_StringArray = 13,
    ThriftDataType_DoubleArray = 14,
    ThriftDataType_FloatArray = 15,
    ThriftDataType_BooleanArray = 16,
    ThriftDataType_ByteArray = 17,
    ThriftDataType_CharacterArray = 18,
    ThriftDataType_LongArray = 19,
    ThriftDataType_ShortArray = 20,
    ThriftDataType_Number = 21,
    ThriftDataType_NumberArray = 22
  };
};

//extern const std::map<int, const char*> _ThriftDataType_VALUES_TO_NAMES;

} // namespace

#endif
