/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ThriftGetGameTypesRequest_TYPES_H
#define ThriftGetGameTypesRequest_TYPES_H

#include <iosfwd>

#include "libs/Thrift.h"

#include "libs/TProtocol.h"
#include "libs/TTransport.h"




namespace es {

class ThriftGetGameTypesRequest;


class ThriftGetGameTypesRequest {
 public:

  ThriftGetGameTypesRequest(const ThriftGetGameTypesRequest&);
  ThriftGetGameTypesRequest& operator=(const ThriftGetGameTypesRequest&);
  ThriftGetGameTypesRequest() {
  }

  virtual ~ThriftGetGameTypesRequest() throw();

  bool operator == (const ThriftGetGameTypesRequest & /* rhs */) const
  {
    return true;
  }
  bool operator != (const ThriftGetGameTypesRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftGetGameTypesRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(ThriftGetGameTypesRequest &a, ThriftGetGameTypesRequest &b);

inline std::ostream& operator<<(std::ostream& out, const ThriftGetGameTypesRequest& obj)
{
  obj.printTo(out);
  return out;
}

} // namespace

#endif
