/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ThriftProtocolConfiguration_types.h"

#include <algorithm>
#include <ostream>

#include "libs/TToString.h"

namespace es {


ThriftProtocolConfiguration::~ThriftProtocolConfiguration() throw() {
}


void ThriftProtocolConfiguration::__set_messageCompressionThreshold(const int32_t val) {
  this->messageCompressionThreshold = val;
}

uint32_t ThriftProtocolConfiguration::read(::apache::thrift::protocol::TProtocol* iprot) {

  apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->messageCompressionThreshold);
          this->__isset.messageCompressionThreshold = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t ThriftProtocolConfiguration::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ThriftProtocolConfiguration");

  xfer += oprot->writeFieldBegin("messageCompressionThreshold", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->messageCompressionThreshold);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ThriftProtocolConfiguration &a, ThriftProtocolConfiguration &b) {
  using ::std::swap;
  swap(a.messageCompressionThreshold, b.messageCompressionThreshold);
  swap(a.__isset, b.__isset);
}

ThriftProtocolConfiguration::ThriftProtocolConfiguration(const ThriftProtocolConfiguration& other0) {
  messageCompressionThreshold = other0.messageCompressionThreshold;
  __isset = other0.__isset;
}
ThriftProtocolConfiguration& ThriftProtocolConfiguration::operator=(const ThriftProtocolConfiguration& other1) {
  messageCompressionThreshold = other1.messageCompressionThreshold;
  __isset = other1.__isset;
  return *this;
}
void ThriftProtocolConfiguration::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ThriftProtocolConfiguration(";
  out << "messageCompressionThreshold=" << to_string(messageCompressionThreshold);
  out << ")";
}

} // namespace
