/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ThriftAddRoomOperatorRequest_TYPES_H
#define ThriftAddRoomOperatorRequest_TYPES_H

#include <iosfwd>

#include "libs/Thrift.h"

#include "libs/TProtocol.h"
#include "libs/TTransport.h"




namespace es {

class ThriftAddRoomOperatorRequest;

typedef struct _ThriftAddRoomOperatorRequest__isset {
  _ThriftAddRoomOperatorRequest__isset() : zoneId(false), roomId(false), userName(false) {}
  bool zoneId :1;
  bool roomId :1;
  bool userName :1;
} _ThriftAddRoomOperatorRequest__isset;

class ThriftAddRoomOperatorRequest {
 public:

  ThriftAddRoomOperatorRequest(const ThriftAddRoomOperatorRequest&);
  ThriftAddRoomOperatorRequest& operator=(const ThriftAddRoomOperatorRequest&);
  ThriftAddRoomOperatorRequest() : zoneId(0), roomId(0), userName() {
  }

  virtual ~ThriftAddRoomOperatorRequest() throw();
  int32_t zoneId;
  int32_t roomId;
  std::string userName;

  _ThriftAddRoomOperatorRequest__isset __isset;

  void __set_zoneId(const int32_t val);

  void __set_roomId(const int32_t val);

  void __set_userName(const std::string& val);

  bool operator == (const ThriftAddRoomOperatorRequest & rhs) const
  {
    if (!(zoneId == rhs.zoneId))
      return false;
    if (!(roomId == rhs.roomId))
      return false;
    if (!(userName == rhs.userName))
      return false;
    return true;
  }
  bool operator != (const ThriftAddRoomOperatorRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftAddRoomOperatorRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(ThriftAddRoomOperatorRequest &a, ThriftAddRoomOperatorRequest &b);

inline std::ostream& operator<<(std::ostream& out, const ThriftAddRoomOperatorRequest& obj)
{
  obj.printTo(out);
  return out;
}

} // namespace

#endif
