/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ThriftDHSharedModulusResponse_TYPES_H
#define ThriftDHSharedModulusResponse_TYPES_H

#include <iosfwd>

#include "libs/Thrift.h"

#include "libs/TProtocol.h"
#include "libs/TTransport.h"




namespace es {

class ThriftDHSharedModulusResponse;

typedef struct _ThriftDHSharedModulusResponse__isset {
  _ThriftDHSharedModulusResponse__isset() : number(false) {}
  bool number :1;
} _ThriftDHSharedModulusResponse__isset;

class ThriftDHSharedModulusResponse {
 public:

  ThriftDHSharedModulusResponse(const ThriftDHSharedModulusResponse&);
  ThriftDHSharedModulusResponse& operator=(const ThriftDHSharedModulusResponse&);
  ThriftDHSharedModulusResponse() : number() {
  }

  virtual ~ThriftDHSharedModulusResponse() throw();
  std::string number;

  _ThriftDHSharedModulusResponse__isset __isset;

  void __set_number(const std::string& val);

  bool operator == (const ThriftDHSharedModulusResponse & rhs) const
  {
    if (!(number == rhs.number))
      return false;
    return true;
  }
  bool operator != (const ThriftDHSharedModulusResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftDHSharedModulusResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(ThriftDHSharedModulusResponse &a, ThriftDHSharedModulusResponse &b);

inline std::ostream& operator<<(std::ostream& out, const ThriftDHSharedModulusResponse& obj)
{
  obj.printTo(out);
  return out;
}

} // namespace

#endif
