/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ThriftUserUpdateAction_TYPES_H
#define ThriftUserUpdateAction_TYPES_H

#include <iosfwd>

#include "libs/Thrift.h"

#include "libs/TProtocol.h"
#include "libs/TTransport.h"




namespace es {

struct ThriftUserUpdateAction {
  enum type {
    ThriftUserUpdateAction_AddUser = 1,
    ThriftUserUpdateAction_DeleteUser = 2,
    ThriftUserUpdateAction_OperatorGranted = 3,
    ThriftUserUpdateAction_OperatorRevoked = 4,
    ThriftUserUpdateAction_SendingVideoStream = 5,
    ThriftUserUpdateAction_StoppingVideoStream = 6
  };
};

//extern const std::map<int, const char*> _ThriftUserUpdateAction_VALUES_TO_NAMES;

} // namespace

#endif
