/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ThriftGetUsersInRoomRequest_TYPES_H
#define ThriftGetUsersInRoomRequest_TYPES_H

#include <iosfwd>

#include "libs/Thrift.h"

#include "libs/TProtocol.h"
#include "libs/TTransport.h"




namespace es {

class ThriftGetUsersInRoomRequest;

typedef struct _ThriftGetUsersInRoomRequest__isset {
  _ThriftGetUsersInRoomRequest__isset() : zoneId(false), roomId(false) {}
  bool zoneId :1;
  bool roomId :1;
} _ThriftGetUsersInRoomRequest__isset;

class ThriftGetUsersInRoomRequest {
 public:

  ThriftGetUsersInRoomRequest(const ThriftGetUsersInRoomRequest&);
  ThriftGetUsersInRoomRequest& operator=(const ThriftGetUsersInRoomRequest&);
  ThriftGetUsersInRoomRequest() : zoneId(0), roomId(0) {
  }

  virtual ~ThriftGetUsersInRoomRequest() throw();
  int32_t zoneId;
  int32_t roomId;

  _ThriftGetUsersInRoomRequest__isset __isset;

  void __set_zoneId(const int32_t val);

  void __set_roomId(const int32_t val);

  bool operator == (const ThriftGetUsersInRoomRequest & rhs) const
  {
    if (!(zoneId == rhs.zoneId))
      return false;
    if (!(roomId == rhs.roomId))
      return false;
    return true;
  }
  bool operator != (const ThriftGetUsersInRoomRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftGetUsersInRoomRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(ThriftGetUsersInRoomRequest &a, ThriftGetUsersInRoomRequest &b);

inline std::ostream& operator<<(std::ostream& out, const ThriftGetUsersInRoomRequest& obj)
{
  obj.printTo(out);
  return out;
}

} // namespace

#endif
