/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ThriftEvictUserFromRoomRequest_TYPES_H
#define ThriftEvictUserFromRoomRequest_TYPES_H

#include <iosfwd>

#include "libs/Thrift.h"

#include "libs/TProtocol.h"
#include "libs/TTransport.h"




namespace es {

class ThriftEvictUserFromRoomRequest;

typedef struct _ThriftEvictUserFromRoomRequest__isset {
  _ThriftEvictUserFromRoomRequest__isset() : zoneId(false), roomId(false), userName(false), reason(false), ban(false), duration(false) {}
  bool zoneId :1;
  bool roomId :1;
  bool userName :1;
  bool reason :1;
  bool ban :1;
  bool duration :1;
} _ThriftEvictUserFromRoomRequest__isset;

class ThriftEvictUserFromRoomRequest {
 public:

  ThriftEvictUserFromRoomRequest(const ThriftEvictUserFromRoomRequest&);
  ThriftEvictUserFromRoomRequest& operator=(const ThriftEvictUserFromRoomRequest&);
  ThriftEvictUserFromRoomRequest() : zoneId(0), roomId(0), userName(), reason(), ban(0), duration(0) {
  }

  virtual ~ThriftEvictUserFromRoomRequest() throw();
  int32_t zoneId;
  int32_t roomId;
  std::string userName;
  std::string reason;
  bool ban;
  int32_t duration;

  _ThriftEvictUserFromRoomRequest__isset __isset;

  void __set_zoneId(const int32_t val);

  void __set_roomId(const int32_t val);

  void __set_userName(const std::string& val);

  void __set_reason(const std::string& val);

  void __set_ban(const bool val);

  void __set_duration(const int32_t val);

  bool operator == (const ThriftEvictUserFromRoomRequest & rhs) const
  {
    if (!(zoneId == rhs.zoneId))
      return false;
    if (!(roomId == rhs.roomId))
      return false;
    if (!(userName == rhs.userName))
      return false;
    if (!(reason == rhs.reason))
      return false;
    if (!(ban == rhs.ban))
      return false;
    if (!(duration == rhs.duration))
      return false;
    return true;
  }
  bool operator != (const ThriftEvictUserFromRoomRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftEvictUserFromRoomRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(ThriftEvictUserFromRoomRequest &a, ThriftEvictUserFromRoomRequest &b);

inline std::ostream& operator<<(std::ostream& out, const ThriftEvictUserFromRoomRequest& obj)
{
  obj.printTo(out);
  return out;
}

} // namespace

#endif
