/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ThriftRegisterUDPConnectionResponse_types.h"

#include <algorithm>
#include <ostream>

#include "libs/TToString.h"

namespace es {


ThriftRegisterUDPConnectionResponse::~ThriftRegisterUDPConnectionResponse() throw() {
}


void ThriftRegisterUDPConnectionResponse::__set_successful(const bool val) {
  this->successful = val;
}

void ThriftRegisterUDPConnectionResponse::__set_sessionKey(const int32_t val) {
  this->sessionKey = val;
}

void ThriftRegisterUDPConnectionResponse::__set_error(const  ::es::ThriftErrorType::type val) {
  this->error = val;
}

uint32_t ThriftRegisterUDPConnectionResponse::read(::apache::thrift::protocol::TProtocol* iprot) {

  apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->successful);
          this->__isset.successful = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->sessionKey);
          this->__isset.sessionKey = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          int32_t ecast0;
          xfer += iprot->readI32(ecast0);
          this->error = ( ::es::ThriftErrorType::type)ecast0;
          this->__isset.error = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t ThriftRegisterUDPConnectionResponse::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ThriftRegisterUDPConnectionResponse");

  xfer += oprot->writeFieldBegin("successful", ::apache::thrift::protocol::T_BOOL, 1);
  xfer += oprot->writeBool(this->successful);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("sessionKey", ::apache::thrift::protocol::T_I32, 2);
  xfer += oprot->writeI32(this->sessionKey);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("error", ::apache::thrift::protocol::T_I32, 3);
  xfer += oprot->writeI32((int32_t)this->error);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ThriftRegisterUDPConnectionResponse &a, ThriftRegisterUDPConnectionResponse &b) {
  using ::std::swap;
  swap(a.successful, b.successful);
  swap(a.sessionKey, b.sessionKey);
  swap(a.error, b.error);
  swap(a.__isset, b.__isset);
}

ThriftRegisterUDPConnectionResponse::ThriftRegisterUDPConnectionResponse(const ThriftRegisterUDPConnectionResponse& other1) {
  successful = other1.successful;
  sessionKey = other1.sessionKey;
  error = other1.error;
  __isset = other1.__isset;
}
ThriftRegisterUDPConnectionResponse& ThriftRegisterUDPConnectionResponse::operator=(const ThriftRegisterUDPConnectionResponse& other2) {
  successful = other2.successful;
  sessionKey = other2.sessionKey;
  error = other2.error;
  __isset = other2.__isset;
  return *this;
}
void ThriftRegisterUDPConnectionResponse::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ThriftRegisterUDPConnectionResponse(";
  out << "successful=" << to_string(successful);
  out << ", " << "sessionKey=" << to_string(sessionKey);
  out << ", " << "error=" << to_string(error);
  out << ")";
}

} // namespace
