/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ThriftUserVariableUpdateAction_TYPES_H
#define ThriftUserVariableUpdateAction_TYPES_H

#include <iosfwd>

#include "libs/Thrift.h"

#include "libs/TProtocol.h"
#include "libs/TTransport.h"




namespace es {

struct ThriftUserVariableUpdateAction {
  enum type {
    ThriftUserVariableUpdateAction_VariableCreated = 1,
    ThriftUserVariableUpdateAction_VariableUpdated = 2,
    ThriftUserVariableUpdateAction_VariableDeleted = 3
  };
};

//extern const std::map<int, const char*> _ThriftUserVariableUpdateAction_VALUES_TO_NAMES;

} // namespace

#endif
