/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ThriftRegisterUDPConnectionRequest_TYPES_H
#define ThriftRegisterUDPConnectionRequest_TYPES_H

#include <iosfwd>

#include "libs/Thrift.h"

#include "libs/TProtocol.h"
#include "libs/TTransport.h"




namespace es {

class ThriftRegisterUDPConnectionRequest;

typedef struct _ThriftRegisterUDPConnectionRequest__isset {
  _ThriftRegisterUDPConnectionRequest__isset() : port(false) {}
  bool port :1;
} _ThriftRegisterUDPConnectionRequest__isset;

class ThriftRegisterUDPConnectionRequest {
 public:

  ThriftRegisterUDPConnectionRequest(const ThriftRegisterUDPConnectionRequest&);
  ThriftRegisterUDPConnectionRequest& operator=(const ThriftRegisterUDPConnectionRequest&);
  ThriftRegisterUDPConnectionRequest() : port(0) {
  }

  virtual ~ThriftRegisterUDPConnectionRequest() throw();
  int32_t port;

  _ThriftRegisterUDPConnectionRequest__isset __isset;

  void __set_port(const int32_t val);

  bool operator == (const ThriftRegisterUDPConnectionRequest & rhs) const
  {
    if (!(port == rhs.port))
      return false;
    return true;
  }
  bool operator != (const ThriftRegisterUDPConnectionRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftRegisterUDPConnectionRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(ThriftRegisterUDPConnectionRequest &a, ThriftRegisterUDPConnectionRequest &b);

inline std::ostream& operator<<(std::ostream& out, const ThriftRegisterUDPConnectionRequest& obj)
{
  obj.printTo(out);
  return out;
}

} // namespace

#endif
