/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ThriftErrorType_TYPES_H
#define ThriftErrorType_TYPES_H

#include <iosfwd>

#include "libs/Thrift.h"

#include "libs/TProtocol.h"
#include "libs/TTransport.h"




namespace es {

struct ThriftErrorType {
  enum type {
    ThriftErrorType_UserNameExists = 1,
    ThriftErrorType_UserAlreadyLoggedIn = 2,
    ThriftErrorType_InvalidMessageNumber = 3,
    ThriftErrorType_InboundMessageFailedValidation = 4,
    ThriftErrorType_MaximumClientConnectionsReached = 5,
    ThriftErrorType_ZoneNotFound = 6,
    ThriftErrorType_RoomNotFound = 7,
    ThriftErrorType_RoomAtCapacity = 8,
    ThriftErrorType_RoomPasswordMismatch = 9,
    ThriftErrorType_GatewayPaused = 10,
    ThriftErrorType_AccessDenied = 11,
    ThriftErrorType_RoomVariableLocked = 12,
    ThriftErrorType_RoomVariableAlreadyExists = 13,
    ThriftErrorType_DuplicateRoomName = 14,
    ThriftErrorType_DuplicateZoneName = 15,
    ThriftErrorType_UserVariableAlreadyExists = 16,
    ThriftErrorType_UserVariableDoesNotExist = 17,
    ThriftErrorType_ZoneAllocationFailure = 18,
    ThriftErrorType_RoomAllocationFailure = 19,
    ThriftErrorType_UserBanned = 20,
    ThriftErrorType_UserAlreadyInRoom = 21,
    ThriftErrorType_LanguageFilterCheckFailed = 22,
    ThriftErrorType_RegistryTransactionEncounteredError = 23,
    ThriftErrorType_ActionRequiresLogin = 24,
    ThriftErrorType_GenericError = 25,
    ThriftErrorType_PluginNotFound = 26,
    ThriftErrorType_LoginEventHandlerFailure = 27,
    ThriftErrorType_InvalidUserName = 28,
    ThriftErrorType_ExtensionNotFound = 29,
    ThriftErrorType_PluginInitializationFailed = 30,
    ThriftErrorType_EventNotFound = 31,
    ThriftErrorType_FloodingFilterCheckFailed = 32,
    ThriftErrorType_UserNotJoinedToRoom = 33,
    ThriftErrorType_ManagedObjectNotFound = 34,
    ThriftErrorType_IdleTimeReached = 35,
    ThriftErrorType_ServerError = 36,
    ThriftErrorType_OperationNotSupported = 37,
    ThriftErrorType_InvalidLanguageFilterSettings = 38,
    ThriftErrorType_InvalidFloodingFilterSettings = 39,
    ThriftErrorType_ExtensionForcedReload = 40,
    ThriftErrorType_UserLogOutRequested = 41,
    ThriftErrorType_OnlyRtmpConnectionRemains = 42,
    ThriftErrorType_GameDoesntExist = 43,
    ThriftErrorType_FailedToJoinGameRoom = 44,
    ThriftErrorType_GameIsLocked = 45,
    ThriftErrorType_InvalidParameters = 46,
    ThriftErrorType_PublicMessageRejected = 47,
    ThriftErrorType_UserKickedFromServer = 48,
    ThriftErrorType_LanguageFilterNotFound = 49,
    ThriftErrorType_InvalidCryptoState = 50,
    ThriftErrorType_FloodingFilterNotFound = 51,
    ThriftErrorType_ConnectionFailed = 52,
    ThriftErrorType_MultipleZonesFound = 53,
    ThriftErrorType_MultipleRoomsFound = 54,
    ThriftErrorType_LoginsAreDisabled = 55,
    ThriftErrorType_ClientDroppedConnection = 56
  };
};

//extern const std::map<int, const char*> _ThriftErrorType_VALUES_TO_NAMES;

} // namespace

#endif
