/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ThriftGetUserCountResponse_types.h"

#include <algorithm>
#include <ostream>

#include "libs/TToString.h"

namespace es {


ThriftGetUserCountResponse::~ThriftGetUserCountResponse() throw() {
}


void ThriftGetUserCountResponse::__set_count(const int32_t val) {
  this->count = val;
}

uint32_t ThriftGetUserCountResponse::read(::apache::thrift::protocol::TProtocol* iprot) {

  apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->count);
          this->__isset.count = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t ThriftGetUserCountResponse::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ThriftGetUserCountResponse");

  xfer += oprot->writeFieldBegin("count", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->count);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ThriftGetUserCountResponse &a, ThriftGetUserCountResponse &b) {
  using ::std::swap;
  swap(a.count, b.count);
  swap(a.__isset, b.__isset);
}

ThriftGetUserCountResponse::ThriftGetUserCountResponse(const ThriftGetUserCountResponse& other0) {
  count = other0.count;
  __isset = other0.__isset;
}
ThriftGetUserCountResponse& ThriftGetUserCountResponse::operator=(const ThriftGetUserCountResponse& other1) {
  count = other1.count;
  __isset = other1.__isset;
  return *this;
}
void ThriftGetUserCountResponse::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ThriftGetUserCountResponse(";
  out << "count=" << to_string(count);
  out << ")";
}

} // namespace
