/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ThriftRemoveBuddiesResponse_types.h"

#include <algorithm>
#include <ostream>

#include "libs/TToString.h"

namespace es {


ThriftRemoveBuddiesResponse::~ThriftRemoveBuddiesResponse() throw() {
}


void ThriftRemoveBuddiesResponse::__set_buddiesRemoved(const std::vector<std::string> & val) {
  this->buddiesRemoved = val;
}

void ThriftRemoveBuddiesResponse::__set_buddiesNotRemoved(const std::vector<std::string> & val) {
  this->buddiesNotRemoved = val;
}

uint32_t ThriftRemoveBuddiesResponse::read(::apache::thrift::protocol::TProtocol* iprot) {

  apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->buddiesRemoved.clear();
            uint32_t _size0;
            ::apache::thrift::protocol::TType _etype3;
            xfer += iprot->readListBegin(_etype3, _size0);
            this->buddiesRemoved.resize(_size0);
            uint32_t _i4;
            for (_i4 = 0; _i4 < _size0; ++_i4)
            {
              xfer += iprot->readString(this->buddiesRemoved[_i4]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.buddiesRemoved = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->buddiesNotRemoved.clear();
            uint32_t _size5;
            ::apache::thrift::protocol::TType _etype8;
            xfer += iprot->readListBegin(_etype8, _size5);
            this->buddiesNotRemoved.resize(_size5);
            uint32_t _i9;
            for (_i9 = 0; _i9 < _size5; ++_i9)
            {
              xfer += iprot->readString(this->buddiesNotRemoved[_i9]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.buddiesNotRemoved = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t ThriftRemoveBuddiesResponse::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ThriftRemoveBuddiesResponse");

  xfer += oprot->writeFieldBegin("buddiesRemoved", ::apache::thrift::protocol::T_LIST, 1);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->buddiesRemoved.size()));
    std::vector<std::string> ::const_iterator _iter10;
    for (_iter10 = this->buddiesRemoved.begin(); _iter10 != this->buddiesRemoved.end(); ++_iter10)
    {
      xfer += oprot->writeString((*_iter10));
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("buddiesNotRemoved", ::apache::thrift::protocol::T_LIST, 2);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->buddiesNotRemoved.size()));
    std::vector<std::string> ::const_iterator _iter11;
    for (_iter11 = this->buddiesNotRemoved.begin(); _iter11 != this->buddiesNotRemoved.end(); ++_iter11)
    {
      xfer += oprot->writeString((*_iter11));
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ThriftRemoveBuddiesResponse &a, ThriftRemoveBuddiesResponse &b) {
  using ::std::swap;
  swap(a.buddiesRemoved, b.buddiesRemoved);
  swap(a.buddiesNotRemoved, b.buddiesNotRemoved);
  swap(a.__isset, b.__isset);
}

ThriftRemoveBuddiesResponse::ThriftRemoveBuddiesResponse(const ThriftRemoveBuddiesResponse& other12) {
  buddiesRemoved = other12.buddiesRemoved;
  buddiesNotRemoved = other12.buddiesNotRemoved;
  __isset = other12.__isset;
}
ThriftRemoveBuddiesResponse& ThriftRemoveBuddiesResponse::operator=(const ThriftRemoveBuddiesResponse& other13) {
  buddiesRemoved = other13.buddiesRemoved;
  buddiesNotRemoved = other13.buddiesNotRemoved;
  __isset = other13.__isset;
  return *this;
}
void ThriftRemoveBuddiesResponse::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ThriftRemoveBuddiesResponse(";
  out << "buddiesRemoved=" << to_string(buddiesRemoved);
  out << ", " << "buddiesNotRemoved=" << to_string(buddiesNotRemoved);
  out << ")";
}

} // namespace
