/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ThriftBuddyStatusUpdateEvent_TYPES_H
#define ThriftBuddyStatusUpdateEvent_TYPES_H

#include <iosfwd>

#include "libs/Thrift.h"

#include "libs/TProtocol.h"
#include "libs/TTransport.h"


#include "ThriftFlattenedEsObject_types.h"
#include "ThriftBuddyStatusUpdateAction_types.h"


namespace es {

class ThriftBuddyStatusUpdateEvent;

typedef struct _ThriftBuddyStatusUpdateEvent__isset {
  _ThriftBuddyStatusUpdateEvent__isset() : userName(false), action(false), esObject(false) {}
  bool userName :1;
  bool action :1;
  bool esObject :1;
} _ThriftBuddyStatusUpdateEvent__isset;

class ThriftBuddyStatusUpdateEvent {
 public:

  ThriftBuddyStatusUpdateEvent(const ThriftBuddyStatusUpdateEvent&);
  ThriftBuddyStatusUpdateEvent& operator=(const ThriftBuddyStatusUpdateEvent&);
  ThriftBuddyStatusUpdateEvent() : userName(), action(( ::es::ThriftBuddyStatusUpdateAction::type)0) {
  }

  virtual ~ThriftBuddyStatusUpdateEvent() throw();
  std::string userName;
   ::es::ThriftBuddyStatusUpdateAction::type action;
   ::es::ThriftFlattenedEsObject esObject;

  _ThriftBuddyStatusUpdateEvent__isset __isset;

  void __set_userName(const std::string& val);

  void __set_action(const  ::es::ThriftBuddyStatusUpdateAction::type val);

  void __set_esObject(const  ::es::ThriftFlattenedEsObject& val);

  bool operator == (const ThriftBuddyStatusUpdateEvent & rhs) const
  {
    if (!(userName == rhs.userName))
      return false;
    if (!(action == rhs.action))
      return false;
    if (!(esObject == rhs.esObject))
      return false;
    return true;
  }
  bool operator != (const ThriftBuddyStatusUpdateEvent &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftBuddyStatusUpdateEvent & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(ThriftBuddyStatusUpdateEvent &a, ThriftBuddyStatusUpdateEvent &b);

inline std::ostream& operator<<(std::ostream& out, const ThriftBuddyStatusUpdateEvent& obj)
{
  obj.printTo(out);
  return out;
}

} // namespace

#endif
