/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ThriftGetZonesRequest_TYPES_H
#define ThriftGetZonesRequest_TYPES_H

#include <iosfwd>

#include "libs/Thrift.h"

#include "libs/TProtocol.h"
#include "libs/TTransport.h"




namespace es {

class ThriftGetZonesRequest;


class ThriftGetZonesRequest {
 public:

  ThriftGetZonesRequest(const ThriftGetZonesRequest&);
  ThriftGetZonesRequest& operator=(const ThriftGetZonesRequest&);
  ThriftGetZonesRequest() {
  }

  virtual ~ThriftGetZonesRequest() throw();

  bool operator == (const ThriftGetZonesRequest & /* rhs */) const
  {
    return true;
  }
  bool operator != (const ThriftGetZonesRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftGetZonesRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(ThriftGetZonesRequest &a, ThriftGetZonesRequest &b);

inline std::ostream& operator<<(std::ostream& out, const ThriftGetZonesRequest& obj)
{
  obj.printTo(out);
  return out;
}

} // namespace

#endif
