/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ThriftConnectionAttemptResponse_TYPES_H
#define ThriftConnectionAttemptResponse_TYPES_H

#include <iosfwd>

#include "libs/Thrift.h"

#include "libs/TProtocol.h"
#include "libs/TTransport.h"


#include "ThriftErrorType_types.h"


namespace es {

class ThriftConnectionAttemptResponse;

typedef struct _ThriftConnectionAttemptResponse__isset {
  _ThriftConnectionAttemptResponse__isset() : successful(false), connectionId(false), error(false) {}
  bool successful :1;
  bool connectionId :1;
  bool error :1;
} _ThriftConnectionAttemptResponse__isset;

class ThriftConnectionAttemptResponse {
 public:

  ThriftConnectionAttemptResponse(const ThriftConnectionAttemptResponse&);
  ThriftConnectionAttemptResponse& operator=(const ThriftConnectionAttemptResponse&);
  ThriftConnectionAttemptResponse() : successful(0), connectionId(0), error(( ::es::ThriftErrorType::type)0) {
  }

  virtual ~ThriftConnectionAttemptResponse() throw();
  bool successful;
  int32_t connectionId;
   ::es::ThriftErrorType::type error;

  _ThriftConnectionAttemptResponse__isset __isset;

  void __set_successful(const bool val);

  void __set_connectionId(const int32_t val);

  void __set_error(const  ::es::ThriftErrorType::type val);

  bool operator == (const ThriftConnectionAttemptResponse & rhs) const
  {
    if (!(successful == rhs.successful))
      return false;
    if (!(connectionId == rhs.connectionId))
      return false;
    if (!(error == rhs.error))
      return false;
    return true;
  }
  bool operator != (const ThriftConnectionAttemptResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftConnectionAttemptResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(ThriftConnectionAttemptResponse &a, ThriftConnectionAttemptResponse &b);

inline std::ostream& operator<<(std::ostream& out, const ThriftConnectionAttemptResponse& obj)
{
  obj.printTo(out);
  return out;
}

} // namespace

#endif
