/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ThriftEvictUserFromRoomRequest_types.h"

#include <algorithm>
#include <ostream>

#include "libs/TToString.h"

namespace es {


ThriftEvictUserFromRoomRequest::~ThriftEvictUserFromRoomRequest() throw() {
}


void ThriftEvictUserFromRoomRequest::__set_zoneId(const int32_t val) {
  this->zoneId = val;
}

void ThriftEvictUserFromRoomRequest::__set_roomId(const int32_t val) {
  this->roomId = val;
}

void ThriftEvictUserFromRoomRequest::__set_userName(const std::string& val) {
  this->userName = val;
}

void ThriftEvictUserFromRoomRequest::__set_reason(const std::string& val) {
  this->reason = val;
}

void ThriftEvictUserFromRoomRequest::__set_ban(const bool val) {
  this->ban = val;
}

void ThriftEvictUserFromRoomRequest::__set_duration(const int32_t val) {
  this->duration = val;
}

uint32_t ThriftEvictUserFromRoomRequest::read(::apache::thrift::protocol::TProtocol* iprot) {

  apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->zoneId);
          this->__isset.zoneId = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->roomId);
          this->__isset.roomId = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->userName);
          this->__isset.userName = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->reason);
          this->__isset.reason = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->ban);
          this->__isset.ban = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 6:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->duration);
          this->__isset.duration = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t ThriftEvictUserFromRoomRequest::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ThriftEvictUserFromRoomRequest");

  xfer += oprot->writeFieldBegin("zoneId", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->zoneId);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("roomId", ::apache::thrift::protocol::T_I32, 2);
  xfer += oprot->writeI32(this->roomId);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("userName", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->userName);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("reason", ::apache::thrift::protocol::T_STRING, 4);
  xfer += oprot->writeString(this->reason);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("ban", ::apache::thrift::protocol::T_BOOL, 5);
  xfer += oprot->writeBool(this->ban);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("duration", ::apache::thrift::protocol::T_I32, 6);
  xfer += oprot->writeI32(this->duration);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ThriftEvictUserFromRoomRequest &a, ThriftEvictUserFromRoomRequest &b) {
  using ::std::swap;
  swap(a.zoneId, b.zoneId);
  swap(a.roomId, b.roomId);
  swap(a.userName, b.userName);
  swap(a.reason, b.reason);
  swap(a.ban, b.ban);
  swap(a.duration, b.duration);
  swap(a.__isset, b.__isset);
}

ThriftEvictUserFromRoomRequest::ThriftEvictUserFromRoomRequest(const ThriftEvictUserFromRoomRequest& other0) {
  zoneId = other0.zoneId;
  roomId = other0.roomId;
  userName = other0.userName;
  reason = other0.reason;
  ban = other0.ban;
  duration = other0.duration;
  __isset = other0.__isset;
}
ThriftEvictUserFromRoomRequest& ThriftEvictUserFromRoomRequest::operator=(const ThriftEvictUserFromRoomRequest& other1) {
  zoneId = other1.zoneId;
  roomId = other1.roomId;
  userName = other1.userName;
  reason = other1.reason;
  ban = other1.ban;
  duration = other1.duration;
  __isset = other1.__isset;
  return *this;
}
void ThriftEvictUserFromRoomRequest::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ThriftEvictUserFromRoomRequest(";
  out << "zoneId=" << to_string(zoneId);
  out << ", " << "roomId=" << to_string(roomId);
  out << ", " << "userName=" << to_string(userName);
  out << ", " << "reason=" << to_string(reason);
  out << ", " << "ban=" << to_string(ban);
  out << ", " << "duration=" << to_string(duration);
  out << ")";
}

} // namespace
