/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ThriftPublicMessageEvent_TYPES_H
#define ThriftPublicMessageEvent_TYPES_H

#include <iosfwd>

#include "libs/Thrift.h"

#include "libs/TProtocol.h"
#include "libs/TTransport.h"


#include "ThriftFlattenedEsObject_types.h"


namespace es {

class ThriftPublicMessageEvent;

typedef struct _ThriftPublicMessageEvent__isset {
  _ThriftPublicMessageEvent__isset() : message(false), userName(false), zoneId(false), roomId(false), esObject(false) {}
  bool message :1;
  bool userName :1;
  bool zoneId :1;
  bool roomId :1;
  bool esObject :1;
} _ThriftPublicMessageEvent__isset;

class ThriftPublicMessageEvent {
 public:

  ThriftPublicMessageEvent(const ThriftPublicMessageEvent&);
  ThriftPublicMessageEvent& operator=(const ThriftPublicMessageEvent&);
  ThriftPublicMessageEvent() : message(), userName(), zoneId(0), roomId(0) {
  }

  virtual ~ThriftPublicMessageEvent() throw();
  std::string message;
  std::string userName;
  int32_t zoneId;
  int32_t roomId;
   ::es::ThriftFlattenedEsObject esObject;

  _ThriftPublicMessageEvent__isset __isset;

  void __set_message(const std::string& val);

  void __set_userName(const std::string& val);

  void __set_zoneId(const int32_t val);

  void __set_roomId(const int32_t val);

  void __set_esObject(const  ::es::ThriftFlattenedEsObject& val);

  bool operator == (const ThriftPublicMessageEvent & rhs) const
  {
    if (__isset.message != rhs.__isset.message)
      return false;
    else if (__isset.message && !(message == rhs.message))
      return false;
    if (__isset.userName != rhs.__isset.userName)
      return false;
    else if (__isset.userName && !(userName == rhs.userName))
      return false;
    if (__isset.zoneId != rhs.__isset.zoneId)
      return false;
    else if (__isset.zoneId && !(zoneId == rhs.zoneId))
      return false;
    if (__isset.roomId != rhs.__isset.roomId)
      return false;
    else if (__isset.roomId && !(roomId == rhs.roomId))
      return false;
    if (__isset.esObject != rhs.__isset.esObject)
      return false;
    else if (__isset.esObject && !(esObject == rhs.esObject))
      return false;
    return true;
  }
  bool operator != (const ThriftPublicMessageEvent &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftPublicMessageEvent & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(ThriftPublicMessageEvent &a, ThriftPublicMessageEvent &b);

inline std::ostream& operator<<(std::ostream& out, const ThriftPublicMessageEvent& obj)
{
  obj.printTo(out);
  return out;
}

} // namespace

#endif
