/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ThriftProtocol_TYPES_H
#define ThriftProtocol_TYPES_H

#include <iosfwd>

#include "libs/Thrift.h"

#include "libs/TProtocol.h"
#include "libs/TTransport.h"




namespace es {

struct ThriftProtocol {
  enum type {
    ThriftProtocol_BinaryTCP = 1,
    ThriftProtocol_RTMP = 2,
    ThriftProtocol_BinaryHTTP = 3,
    ThriftProtocol_TextTCP = 4,
    ThriftProtocol_BinaryUDP = 5
  };
};

//extern const std::map<int, const char*> _ThriftProtocol_VALUES_TO_NAMES;

} // namespace

#endif
