/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ThriftZoneUpdateAction_TYPES_H
#define ThriftZoneUpdateAction_TYPES_H

namespace es {

struct ThriftZoneUpdateAction {
  enum type {
    AddRoom = 1,
    DeleteRoom = 2,
    UpdateRoom = 3
  };
};

//extern const std::map<int, const char*> _ThriftZoneUpdateAction_VALUES_TO_NAMES;

} // namespace

#endif
