/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ThriftGetZonesResponse_types.h"

#include <algorithm>
#include <ostream>

#include "libs/TToString.h"

namespace es {


ThriftGetZonesResponse::~ThriftGetZonesResponse() throw() {
}


void ThriftGetZonesResponse::__set_zones(const std::vector< ::es::ThriftZoneListEntry> & val) {
  this->zones = val;
}

uint32_t ThriftGetZonesResponse::read(::apache::thrift::protocol::TProtocol* iprot) {

  apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->zones.clear();
            uint32_t _size0;
            ::apache::thrift::protocol::TType _etype3;
            xfer += iprot->readListBegin(_etype3, _size0);
            this->zones.resize(_size0);
            uint32_t _i4;
            for (_i4 = 0; _i4 < _size0; ++_i4)
            {
              xfer += this->zones[_i4].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.zones = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t ThriftGetZonesResponse::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ThriftGetZonesResponse");

  xfer += oprot->writeFieldBegin("zones", ::apache::thrift::protocol::T_LIST, 1);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->zones.size()));
    std::vector< ::es::ThriftZoneListEntry> ::const_iterator _iter5;
    for (_iter5 = this->zones.begin(); _iter5 != this->zones.end(); ++_iter5)
    {
      xfer += (*_iter5).write(oprot);
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ThriftGetZonesResponse &a, ThriftGetZonesResponse &b) {
  using ::std::swap;
  swap(a.zones, b.zones);
  swap(a.__isset, b.__isset);
}

ThriftGetZonesResponse::ThriftGetZonesResponse(const ThriftGetZonesResponse& other6) {
  zones = other6.zones;
  __isset = other6.__isset;
}
ThriftGetZonesResponse& ThriftGetZonesResponse::operator=(const ThriftGetZonesResponse& other7) {
  zones = other7.zones;
  __isset = other7.__isset;
  return *this;
}
void ThriftGetZonesResponse::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ThriftGetZonesResponse(";
  out << "zones=" << to_string(zones);
  out << ")";
}

} // namespace
