/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ThriftRemoveBuddiesRequest_types.h"

#include <algorithm>
#include <ostream>

#include "libs/TToString.h"

namespace es {


ThriftRemoveBuddiesRequest::~ThriftRemoveBuddiesRequest() throw() {
}


void ThriftRemoveBuddiesRequest::__set_buddyNames(const std::vector<std::string> & val) {
  this->buddyNames = val;
}

uint32_t ThriftRemoveBuddiesRequest::read(::apache::thrift::protocol::TProtocol* iprot) {

  apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->buddyNames.clear();
            uint32_t _size0;
            ::apache::thrift::protocol::TType _etype3;
            xfer += iprot->readListBegin(_etype3, _size0);
            this->buddyNames.resize(_size0);
            uint32_t _i4;
            for (_i4 = 0; _i4 < _size0; ++_i4)
            {
              xfer += iprot->readString(this->buddyNames[_i4]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.buddyNames = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t ThriftRemoveBuddiesRequest::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ThriftRemoveBuddiesRequest");

  xfer += oprot->writeFieldBegin("buddyNames", ::apache::thrift::protocol::T_LIST, 1);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->buddyNames.size()));
    std::vector<std::string> ::const_iterator _iter5;
    for (_iter5 = this->buddyNames.begin(); _iter5 != this->buddyNames.end(); ++_iter5)
    {
      xfer += oprot->writeString((*_iter5));
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ThriftRemoveBuddiesRequest &a, ThriftRemoveBuddiesRequest &b) {
  using ::std::swap;
  swap(a.buddyNames, b.buddyNames);
  swap(a.__isset, b.__isset);
}

ThriftRemoveBuddiesRequest::ThriftRemoveBuddiesRequest(const ThriftRemoveBuddiesRequest& other6) {
  buddyNames = other6.buddyNames;
  __isset = other6.__isset;
}
ThriftRemoveBuddiesRequest& ThriftRemoveBuddiesRequest::operator=(const ThriftRemoveBuddiesRequest& other7) {
  buddyNames = other7.buddyNames;
  __isset = other7.__isset;
  return *this;
}
void ThriftRemoveBuddiesRequest::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ThriftRemoveBuddiesRequest(";
  out << "buddyNames=" << to_string(buddyNames);
  out << ")";
}

} // namespace
