/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ThriftGetRoomsInZoneResponse_TYPES_H
#define ThriftGetRoomsInZoneResponse_TYPES_H

#include <iosfwd>

#include "libs/Thrift.h"

#include "libs/TProtocol.h"
#include "libs/TTransport.h"


#include "ThriftRoomListEntry_types.h"


namespace es {

class ThriftGetRoomsInZoneResponse;

typedef struct _ThriftGetRoomsInZoneResponse__isset {
  _ThriftGetRoomsInZoneResponse__isset() : zoneId(false), zoneName(false), entries(false) {}
  bool zoneId :1;
  bool zoneName :1;
  bool entries :1;
} _ThriftGetRoomsInZoneResponse__isset;

class ThriftGetRoomsInZoneResponse {
 public:

  ThriftGetRoomsInZoneResponse(const ThriftGetRoomsInZoneResponse&);
  ThriftGetRoomsInZoneResponse& operator=(const ThriftGetRoomsInZoneResponse&);
  ThriftGetRoomsInZoneResponse() : zoneId(0), zoneName() {
  }

  virtual ~ThriftGetRoomsInZoneResponse() throw();
  int32_t zoneId;
  std::string zoneName;
  std::vector< ::es::ThriftRoomListEntry>  entries;

  _ThriftGetRoomsInZoneResponse__isset __isset;

  void __set_zoneId(const int32_t val);

  void __set_zoneName(const std::string& val);

  void __set_entries(const std::vector< ::es::ThriftRoomListEntry> & val);

  bool operator == (const ThriftGetRoomsInZoneResponse & rhs) const
  {
    if (!(zoneId == rhs.zoneId))
      return false;
    if (!(zoneName == rhs.zoneName))
      return false;
    if (!(entries == rhs.entries))
      return false;
    return true;
  }
  bool operator != (const ThriftGetRoomsInZoneResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftGetRoomsInZoneResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(ThriftGetRoomsInZoneResponse &a, ThriftGetRoomsInZoneResponse &b);

inline std::ostream& operator<<(std::ostream& out, const ThriftGetRoomsInZoneResponse& obj)
{
  obj.printTo(out);
  return out;
}

} // namespace

#endif
