/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ThriftRegistryConnectToPreferredGatewayRequest_types.h"

#include <algorithm>
#include <ostream>

#include "libs/TToString.h"

namespace es {


ThriftRegistryConnectToPreferredGatewayRequest::~ThriftRegistryConnectToPreferredGatewayRequest() throw() {
}


void ThriftRegistryConnectToPreferredGatewayRequest::__set_zoneId(const int32_t val) {
  this->zoneId = val;
}

void ThriftRegistryConnectToPreferredGatewayRequest::__set_host(const std::string& val) {
  this->host = val;
}

void ThriftRegistryConnectToPreferredGatewayRequest::__set_port(const int32_t val) {
  this->port = val;
}

void ThriftRegistryConnectToPreferredGatewayRequest::__set_protocolToUse(const  ::es::ThriftProtocol::type val) {
  this->protocolToUse = val;
}

uint32_t ThriftRegistryConnectToPreferredGatewayRequest::read(::apache::thrift::protocol::TProtocol* iprot) {

  apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->zoneId);
          this->__isset.zoneId = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->host);
          this->__isset.host = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->port);
          this->__isset.port = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          int32_t ecast0;
          xfer += iprot->readI32(ecast0);
          this->protocolToUse = ( ::es::ThriftProtocol::type)ecast0;
          this->__isset.protocolToUse = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t ThriftRegistryConnectToPreferredGatewayRequest::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ThriftRegistryConnectToPreferredGatewayRequest");

  xfer += oprot->writeFieldBegin("zoneId", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->zoneId);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("host", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->host);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("port", ::apache::thrift::protocol::T_I32, 3);
  xfer += oprot->writeI32(this->port);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("protocolToUse", ::apache::thrift::protocol::T_I32, 4);
  xfer += oprot->writeI32((int32_t)this->protocolToUse);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ThriftRegistryConnectToPreferredGatewayRequest &a, ThriftRegistryConnectToPreferredGatewayRequest &b) {
  using ::std::swap;
  swap(a.zoneId, b.zoneId);
  swap(a.host, b.host);
  swap(a.port, b.port);
  swap(a.protocolToUse, b.protocolToUse);
  swap(a.__isset, b.__isset);
}

ThriftRegistryConnectToPreferredGatewayRequest::ThriftRegistryConnectToPreferredGatewayRequest(const ThriftRegistryConnectToPreferredGatewayRequest& other1) {
  zoneId = other1.zoneId;
  host = other1.host;
  port = other1.port;
  protocolToUse = other1.protocolToUse;
  __isset = other1.__isset;
}
ThriftRegistryConnectToPreferredGatewayRequest& ThriftRegistryConnectToPreferredGatewayRequest::operator=(const ThriftRegistryConnectToPreferredGatewayRequest& other2) {
  zoneId = other2.zoneId;
  host = other2.host;
  port = other2.port;
  protocolToUse = other2.protocolToUse;
  __isset = other2.__isset;
  return *this;
}
void ThriftRegistryConnectToPreferredGatewayRequest::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ThriftRegistryConnectToPreferredGatewayRequest(";
  out << "zoneId=" << to_string(zoneId);
  out << ", " << "host=" << to_string(host);
  out << ", " << "port=" << to_string(port);
  out << ", " << "protocolToUse=" << to_string(protocolToUse);
  out << ")";
}

} // namespace
