/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ThriftPingRequest_TYPES_H
#define ThriftPingRequest_TYPES_H

#include <iosfwd>

#include "libs/Thrift.h"

#include "libs/TProtocol.h"
#include "libs/TTransport.h"



namespace es {

class ThriftPingRequest;

typedef struct _ThriftPingRequest__isset {
  _ThriftPingRequest__isset() : globalResponseRequested(false), sessionKey(false), pingRequestId(false) {}
  bool globalResponseRequested :1;
  bool sessionKey :1;
  bool pingRequestId :1;
} _ThriftPingRequest__isset;

class ThriftPingRequest {
 public:

  ThriftPingRequest(const ThriftPingRequest&);
  ThriftPingRequest& operator=(const ThriftPingRequest&);
  ThriftPingRequest() : globalResponseRequested(0), sessionKey(0), pingRequestId(0) {
  }

  virtual ~ThriftPingRequest() throw();
  bool globalResponseRequested;
  int32_t sessionKey;
  int32_t pingRequestId;

  _ThriftPingRequest__isset __isset;

  void __set_globalResponseRequested(const bool val);

  void __set_sessionKey(const int32_t val);

  void __set_pingRequestId(const int32_t val);

  bool operator == (const ThriftPingRequest & rhs) const
  {
    if (__isset.globalResponseRequested != rhs.__isset.globalResponseRequested)
      return false;
    else if (__isset.globalResponseRequested && !(globalResponseRequested == rhs.globalResponseRequested))
      return false;
    if (__isset.sessionKey != rhs.__isset.sessionKey)
      return false;
    else if (__isset.sessionKey && !(sessionKey == rhs.sessionKey))
      return false;
    if (__isset.pingRequestId != rhs.__isset.pingRequestId)
      return false;
    else if (__isset.pingRequestId && !(pingRequestId == rhs.pingRequestId))
      return false;
    return true;
  }
  bool operator != (const ThriftPingRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftPingRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(ThriftPingRequest &a, ThriftPingRequest &b);

inline std::ostream& operator<<(std::ostream& out, const ThriftPingRequest& obj)
{
  obj.printTo(out);
  return out;
}

} // namespace

#endif
