/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ThriftLeaveRoomEvent_TYPES_H
#define ThriftLeaveRoomEvent_TYPES_H

#include <iosfwd>

#include "libs/Thrift.h"

#include "libs/TProtocol.h"
#include "libs/TTransport.h"




namespace es {

class ThriftLeaveRoomEvent;

typedef struct _ThriftLeaveRoomEvent__isset {
  _ThriftLeaveRoomEvent__isset() : zoneId(false), roomId(false) {}
  bool zoneId :1;
  bool roomId :1;
} _ThriftLeaveRoomEvent__isset;

class ThriftLeaveRoomEvent {
 public:

  ThriftLeaveRoomEvent(const ThriftLeaveRoomEvent&);
  ThriftLeaveRoomEvent& operator=(const ThriftLeaveRoomEvent&);
  ThriftLeaveRoomEvent() : zoneId(0), roomId(0) {
  }

  virtual ~ThriftLeaveRoomEvent() throw();
  int32_t zoneId;
  int32_t roomId;

  _ThriftLeaveRoomEvent__isset __isset;

  void __set_zoneId(const int32_t val);

  void __set_roomId(const int32_t val);

  bool operator == (const ThriftLeaveRoomEvent & rhs) const
  {
    if (__isset.zoneId != rhs.__isset.zoneId)
      return false;
    else if (__isset.zoneId && !(zoneId == rhs.zoneId))
      return false;
    if (__isset.roomId != rhs.__isset.roomId)
      return false;
    else if (__isset.roomId && !(roomId == rhs.roomId))
      return false;
    return true;
  }
  bool operator != (const ThriftLeaveRoomEvent &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftLeaveRoomEvent & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(ThriftLeaveRoomEvent &a, ThriftLeaveRoomEvent &b);

inline std::ostream& operator<<(std::ostream& out, const ThriftLeaveRoomEvent& obj)
{
  obj.printTo(out);
  return out;
}

} // namespace

#endif
