/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ThriftCreateRoomVariableRequest_types.h"

#include <algorithm>
#include <ostream>

#include "libs/TToString.h"

namespace es {


ThriftCreateRoomVariableRequest::~ThriftCreateRoomVariableRequest() throw() {
}


void ThriftCreateRoomVariableRequest::__set_zoneId(const int32_t val) {
  this->zoneId = val;
}

void ThriftCreateRoomVariableRequest::__set_roomId(const int32_t val) {
  this->roomId = val;
}

void ThriftCreateRoomVariableRequest::__set_name(const std::string& val) {
  this->name = val;
}

void ThriftCreateRoomVariableRequest::__set_value(const  ::es::ThriftFlattenedEsObject& val) {
  this->value = val;
}

void ThriftCreateRoomVariableRequest::__set_locked(const bool val) {
  this->locked = val;
}

void ThriftCreateRoomVariableRequest::__set_persistent(const bool val) {
  this->persistent = val;
}

uint32_t ThriftCreateRoomVariableRequest::read(::apache::thrift::protocol::TProtocol* iprot) {

  apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->zoneId);
          this->__isset.zoneId = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->roomId);
          this->__isset.roomId = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->name);
          this->__isset.name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->value.read(iprot);
          this->__isset.value = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->locked);
          this->__isset.locked = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 6:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->persistent);
          this->__isset.persistent = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t ThriftCreateRoomVariableRequest::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ThriftCreateRoomVariableRequest");

  xfer += oprot->writeFieldBegin("zoneId", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->zoneId);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("roomId", ::apache::thrift::protocol::T_I32, 2);
  xfer += oprot->writeI32(this->roomId);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("name", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->name);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("value", ::apache::thrift::protocol::T_STRUCT, 4);
  xfer += this->value.write(oprot);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("locked", ::apache::thrift::protocol::T_BOOL, 5);
  xfer += oprot->writeBool(this->locked);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("persistent", ::apache::thrift::protocol::T_BOOL, 6);
  xfer += oprot->writeBool(this->persistent);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ThriftCreateRoomVariableRequest &a, ThriftCreateRoomVariableRequest &b) {
  using ::std::swap;
  swap(a.zoneId, b.zoneId);
  swap(a.roomId, b.roomId);
  swap(a.name, b.name);
  swap(a.value, b.value);
  swap(a.locked, b.locked);
  swap(a.persistent, b.persistent);
  swap(a.__isset, b.__isset);
}

ThriftCreateRoomVariableRequest::ThriftCreateRoomVariableRequest(const ThriftCreateRoomVariableRequest& other0) {
  zoneId = other0.zoneId;
  roomId = other0.roomId;
  name = other0.name;
  value = other0.value;
  locked = other0.locked;
  persistent = other0.persistent;
  __isset = other0.__isset;
}
ThriftCreateRoomVariableRequest& ThriftCreateRoomVariableRequest::operator=(const ThriftCreateRoomVariableRequest& other1) {
  zoneId = other1.zoneId;
  roomId = other1.roomId;
  name = other1.name;
  value = other1.value;
  locked = other1.locked;
  persistent = other1.persistent;
  __isset = other1.__isset;
  return *this;
}
void ThriftCreateRoomVariableRequest::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ThriftCreateRoomVariableRequest(";
  out << "zoneId=" << to_string(zoneId);
  out << ", " << "roomId=" << to_string(roomId);
  out << ", " << "name=" << to_string(name);
  out << ", " << "value=" << to_string(value);
  out << ", " << "locked=" << to_string(locked);
  out << ", " << "persistent=" << to_string(persistent);
  out << ")";
}

} // namespace
