/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ThriftDHSharedModulusResponse_types.h"

#include <algorithm>
#include <ostream>

#include "libs/TToString.h"

namespace es {


ThriftDHSharedModulusResponse::~ThriftDHSharedModulusResponse() throw() {
}


void ThriftDHSharedModulusResponse::__set_number(const std::string& val) {
  this->number = val;
}

uint32_t ThriftDHSharedModulusResponse::read(::apache::thrift::protocol::TProtocol* iprot) {

  apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->number);
          this->__isset.number = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t ThriftDHSharedModulusResponse::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ThriftDHSharedModulusResponse");

  xfer += oprot->writeFieldBegin("number", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->number);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ThriftDHSharedModulusResponse &a, ThriftDHSharedModulusResponse &b) {
  using ::std::swap;
  swap(a.number, b.number);
  swap(a.__isset, b.__isset);
}

ThriftDHSharedModulusResponse::ThriftDHSharedModulusResponse(const ThriftDHSharedModulusResponse& other0) {
  number = other0.number;
  __isset = other0.__isset;
}
ThriftDHSharedModulusResponse& ThriftDHSharedModulusResponse::operator=(const ThriftDHSharedModulusResponse& other1) {
  number = other1.number;
  __isset = other1.__isset;
  return *this;
}
void ThriftDHSharedModulusResponse::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ThriftDHSharedModulusResponse(";
  out << "number=" << to_string(number);
  out << ")";
}

} // namespace
