/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ThriftGetUserCountRequest_TYPES_H
#define ThriftGetUserCountRequest_TYPES_H

#include <iosfwd>

#include "libs/Thrift.h"

#include "libs/TProtocol.h"
#include "libs/TTransport.h"




namespace es {

class ThriftGetUserCountRequest;


class ThriftGetUserCountRequest {
 public:

  ThriftGetUserCountRequest(const ThriftGetUserCountRequest&);
  ThriftGetUserCountRequest& operator=(const ThriftGetUserCountRequest&);
  ThriftGetUserCountRequest() {
  }

  virtual ~ThriftGetUserCountRequest() throw();

  bool operator == (const ThriftGetUserCountRequest & /* rhs */) const
  {
    return true;
  }
  bool operator != (const ThriftGetUserCountRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftGetUserCountRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(ThriftGetUserCountRequest &a, ThriftGetUserCountRequest &b);

inline std::ostream& operator<<(std::ostream& out, const ThriftGetUserCountRequest& obj)
{
  obj.printTo(out);
  return out;
}

} // namespace

#endif
