/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ThriftRoomVariableUpdateAction_types.h"

#include <algorithm>
#include <ostream>

#include "libs/TToString.h"

namespace es {

//int _kThriftRoomVariableUpdateActionValues[] = {
//  ThriftRoomVariableUpdateAction::ThriftRoomVariableUpdateAction_VariableCreated,
//  ThriftRoomVariableUpdateAction::ThriftRoomVariableUpdateAction_VariableUpdated,
//  ThriftRoomVariableUpdateAction::ThriftRoomVariableUpdateAction_VariableDeleted
//};
//const char* _kThriftRoomVariableUpdateActionNames[] = {
//  "ThriftRoomVariableUpdateAction_VariableCreated",
//  "ThriftRoomVariableUpdateAction_VariableUpdated",
//  "ThriftRoomVariableUpdateAction_VariableDeleted"
//};
//const std::map<int, const char*> _ThriftRoomVariableUpdateAction_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(3, _kThriftRoomVariableUpdateActionValues, _kThriftRoomVariableUpdateActionNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));

} // namespace
