/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ThriftZoneListEntry_TYPES_H
#define ThriftZoneListEntry_TYPES_H

#include <iosfwd>

#include "libs/Thrift.h"

#include "libs/TProtocol.h"
#include "libs/TTransport.h"




namespace es {

class ThriftZoneListEntry;

typedef struct _ThriftZoneListEntry__isset {
  _ThriftZoneListEntry__isset() : zoneId(false), zoneName(false) {}
  bool zoneId :1;
  bool zoneName :1;
} _ThriftZoneListEntry__isset;

class ThriftZoneListEntry {
 public:

  ThriftZoneListEntry(const ThriftZoneListEntry&);
  ThriftZoneListEntry& operator=(const ThriftZoneListEntry&);
  ThriftZoneListEntry() : zoneId(0), zoneName() {
  }

  virtual ~ThriftZoneListEntry() throw();
  int32_t zoneId;
  std::string zoneName;

  _ThriftZoneListEntry__isset __isset;

  void __set_zoneId(const int32_t val);

  void __set_zoneName(const std::string& val);

  bool operator == (const ThriftZoneListEntry & rhs) const
  {
    if (!(zoneId == rhs.zoneId))
      return false;
    if (!(zoneName == rhs.zoneName))
      return false;
    return true;
  }
  bool operator != (const ThriftZoneListEntry &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftZoneListEntry & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(ThriftZoneListEntry &a, ThriftZoneListEntry &b);

inline std::ostream& operator<<(std::ostream& out, const ThriftZoneListEntry& obj)
{
  obj.printTo(out);
  return out;
}

} // namespace

#endif
