/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ThriftValidateAdditionalLoginRequest_types.h"

#include <algorithm>
#include <ostream>

#include "libs/TToString.h"

namespace es {


ThriftValidateAdditionalLoginRequest::~ThriftValidateAdditionalLoginRequest() throw() {
}


void ThriftValidateAdditionalLoginRequest::__set_secret(const std::string& val) {
  this->secret = val;
}

uint32_t ThriftValidateAdditionalLoginRequest::read(::apache::thrift::protocol::TProtocol* iprot) {

  apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->secret);
          this->__isset.secret = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t ThriftValidateAdditionalLoginRequest::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ThriftValidateAdditionalLoginRequest");

  xfer += oprot->writeFieldBegin("secret", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->secret);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ThriftValidateAdditionalLoginRequest &a, ThriftValidateAdditionalLoginRequest &b) {
  using ::std::swap;
  swap(a.secret, b.secret);
  swap(a.__isset, b.__isset);
}

ThriftValidateAdditionalLoginRequest::ThriftValidateAdditionalLoginRequest(const ThriftValidateAdditionalLoginRequest& other0) {
  secret = other0.secret;
  __isset = other0.__isset;
}
ThriftValidateAdditionalLoginRequest& ThriftValidateAdditionalLoginRequest::operator=(const ThriftValidateAdditionalLoginRequest& other1) {
  secret = other1.secret;
  __isset = other1.__isset;
  return *this;
}
void ThriftValidateAdditionalLoginRequest::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ThriftValidateAdditionalLoginRequest(";
  out << "secret=" << to_string(secret);
  out << ")";
}

} // namespace
