/**
 * Created by Quyet Nguyen on 8/2/2016.
 */

require("js/Global/Global.js");
require("js/Core/NewAction.js");
require("js/Core/ToggleNodeGroup.js");
require("js/Core/ButtonToggle.js");
require("js/Socket/LobbyClient.js");
require("js/Socket/LobbyError.js");
require("js/Socket/SmartfoxClient.js");
require("js/Global/UserAvatar.js");
require("js/Dialog/Dialog.js");
require("js/Dialog/MessageDialog.js");
require("js/Dialog/InviteDialog.js");
require("js/Dialog/LoadingDialog.js");
require("js/Dialog/MessageNode.js");
require("js/Dialog/ResultDialog.js");
require("js/Dialog/SettingDialog.js");
require("js/Dialog/UserDialog.js");
require("js/Dialog/UserinfoDialog.js");
require("js/Dialog/UserListDialog.js");
require("js/Dialog/RewardDialog.js");
require("js/app.js");
require("js/IScene.js");
require("js/Home/LobbySubLayer.js");
require("js/Home/LobbyTopBar.js");
require("js/Home/LobbyBottomBar.js");
require("js/Home/HomeLayer.js");
require("js/Home/HomeScene.js");
require("js/Home/GameLayer.js");
require("js/Home/LobbyLayer.js");
require("js/Home/MiniGameLayer.js");
require("js/Home/NewsLayer.js");
require("js/Home/PaymentLayer.js");
require("js/Home/RankLayer.js");
require("js/Home/RewardLayer.js");
require("js/Home/InboxLayer.js");
require("js/Game/Card.js");
require("js/Game/GamePlayer.js");
require("js/Game/GameScene.js");
require("js/Game/TienLen.js");
require("js/Game/BaCay.js");
require("js/Game/BaCayChuong.js");
require("js/Game/MauBinh.js");
require("js/Game/Phom.js");
require("js/Game/Sam.js");
require("js/Game/TaiXiu.js");
require("js/Game/XocDia.js");